### ISSUE TITLE
[Question] MAG quality score

### ISSUE THREAD

**Issue by apcamargo** [wwood/galah#1]
Hi Ben

In the documentation it is said that "*Each representative genome has a better quality score than other members of the cluster"*. How is the quality score computed? Does it use only contamination/completeness or it also incorporates contiguity metrics (as dRep does)?

Thank you!

**Comment by wwood** [comment]
Hi,

Thanks for your interest. It scores each genome according to completeness - 4* contamination. I've added a note for that in the README.

I'm not quite sure what you mean by contiguity metrics - can you be more specific?
Thanks.

**Comment by apcamargo** [comment]
dRep's score formula is:

```
score = A*(completeness) – B*(contamination) + C*(Contamination * (Strain heterogeneity / 100)) + D*(log(N50)) + E(log(size))
```

Where `A`, `B`, `C`, `D` and `E` are adjustable weights (defaults: `1`, `5,` `1`, `0.5`, `0`).

So, by default, they take the N50 into consideration to compute the score. I'm unsure if that is the best option because of two things:
1. In my opinion, the N50 is an unfit metric to compare the contiguity between MAGs that may have very different assembly sizes. I would use something like the logsum.
2. It seems to me that if the N50 is large, the relative contribution of the completeness and contamination would be diminished. But it would require some testing to confirm that.

**Comment by wwood** [comment]
Thanks for that food for thought. I'll have a think.

**Comment by apcamargo** [comment]
By the way, the logsum formula is:
```
Σ log2(L/1000), if L > 1000
```
I like it because it downweights short contigs so a big and fragmented assembly will have a worse score than a slightly smaller but more contiguous one.

**Comment by wwood** [comment]
Hi again,

Since it is (pre-)published I added `--quality-formula Parks2020_reduced` to the cluster subcommand in the master branch. Do you think that suffices? The formula is `completeness-5*contamination-5*num_contigs/100-5*num_ambiguous_bases/100000`.

As a workaround, you can simply provide the genomes sorted highest to lowest quaity as input e.g. with `--genome-fasta-list`, so you are ultimately free to define whatever quality metric you feel best.

ta, ben

**Comment by wwood** [comment]
I also just added `--quality-formala dRep` implementing the default dRep scoring criteria.

**Comment by wwood** [comment]
The other thing is, if you want to write your own formula, you can run `RUST_LOG=galah galah cluster` and in the debug statements will be the N50, completeness etc. calculated for you.

**Comment by apcamargo** [comment]
I'll test the formula from Donovan's paper later. I guess they ajusted it so that `5*num_contigs/100` and `num_ambiguous_bases/100000` are in the same scale as `completeness-5*contamination`.

Thank you for the effort you put into this!
