### ISSUE TITLE
skani is not parallelized in `galah cluster`

### ISSUE THREAD

**Issue by apcamargo** [wwood/galah#36]
I'm trying out the latest Galah commit and I noticed that is is using a single thread to cluster genomes, even though I set `--threads 48`. Is this by design?

**Comment by wwood** [comment]
Hi,

Good point - and a reminder to fix this - @AroneyS reported this offline a few weeks back.

Have implemented a fix but it could do with some more real world testing - does it work for you?
Thanks.

**Comment by wwood** [comment]
Looks like it might be a bit slow at the moment because it repeatedly recalculates sketches.
