### ISSUE TITLE
error: unexpected argument '-d' found

### ISSUE THREAD

**Issue by xvazquezc** [wwood/galah#44]
Hi there,

it seems that the short option for `--genome-fasta-directory` in `galah cluster` isn't being recognised. The `--full-help` also shows a missing dash in the option:
```
       d, --genome-fasta-directory PATH
              Directory containing FASTA files of each genome.
```
I'm using galah v0.4.0

Cheers

**Comment by wwood** [comment]
Thanks @xvazquezc - @AroneyS can you have a look please?

**Comment by wwood** [comment]
thanks both, it will be fixed in the next release
